#resolver: lts-9.21   # ghc-8.0.2
#resolver: lts-11.22  # ghc-8.2.2
#resolver: lts-12.26  # ghc-8.4.4
#resolver: lts-14.27  # ghc-8.6.5
#resolver: lts-16.31  # ghc-8.8.4
#resolver: lts-18.28  # ghc-8.10.7
#resolver: lts-19.33  # ghc-9.0.2
#resolver: lts-20.26  # ghc-9.2.8
#resolver: lts-21.25  # ghc-9.4.8
resolver: lts-22.22  # ghc-9.6.5
#resolver: nightly-2024-05-16 # ghc-9.8.2

packages:
- .
extra-deps:
- ms-tds-0.4.0.3
#- ../ms-tds
